name: Build

on:
  push:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      matrix:
        rid: [any, linux-arm, linux-arm64, linux-x64, osx-x64, win-x64]
        build_configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore Packages
        run: dotnet restore -v m
      - name: Build CLI
        if: ${{ matrix.rid == 'any' }}
        run: dotnet publish -c ${{ matrix.build_configuration }} FlvInteractiveRebase/FlvInteractiveRebase.csproj
      - name: Build CLI
        if: ${{ matrix.rid != 'any' }}
        run: dotnet publish -c ${{ matrix.build_configuration }} -r ${{ matrix.rid }} FlvInteractiveRebase/FlvInteractiveRebase.csproj
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FIR-${{ matrix.rid }}-${{ matrix.build_configuration }}
          path: FlvInteractiveRebase/publish/${{ matrix.rid }}
